{"uuid": "f4056ae2-9529-4c1c-a353-41e58b1d54c2", "children": ["29bbf66b-24b5-4850-a92d-6c8f37cfc3dd"], "befores": [{"name": "read_config_file", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../Config/config.json'\n", "trace": "  File \"C:\\Python39\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1124, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 930, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\PythonSelenium\\Tests\\conftest.py\", line 17, in read_config_file\n    with open(CONFIG_PATH) as config_file:\n"}, "start": 1605455227605, "stop": 1605455227606}], "start": 1605455227605, "stop": 1605455227991}