{"name": "test_if_site_url_is_correct", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../Config/config.json'", "trace": "@pytest.fixture(scope='session', autouse=True)\n    def read_config_file():\n>       with open(CONFIG_PATH) as config_file:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../Config/config.json'\n\nTests\\conftest.py:17: FileNotFoundError"}, "description": "Checking that app URL is correct", "start": 1605455227604, "stop": 1605455227604, "uuid": "6f2e8246-b06e-4626-bd11-f9c47ce36ebd", "historyId": "67e3d58cbb28af217236a9cedfa4f1e5", "testCaseId": "c9b8aa90e54b85d475fc750c19168736", "fullName": "Tests.test_basic.TestBasic#test_if_site_url_is_correct", "labels": [{"name": "severity", "value": "trivial"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_basic"}, {"name": "subSuite", "value": "TestBasic"}, {"name": "host", "value": "RAP-PF0TKNDX"}, {"name": "thread", "value": "16452-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_basic"}]}